### ISSUE TITLE
Diagram still uses "SRML"

### ISSUE THREAD

**Issue by JoshOrndorff** [substrate-developer-hub/substrate-cms#10]
The diagram at https://substrate.dev/docs/en/#usage still mentions the "SRML". That should be changed to "FRAME".

The file itself is https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/blob/source/docs/assets/technical-freedom.png

**Comment by joepetrowski** [comment]
Got rid of this image at least in the current version of KB.
