### ISSUE TITLE
Substrate Runtime Module Development vs Ethereum Smart Contract Development

### ISSUE THREAD

**Issue by shawntabrizi** [substrate-developer-hub/substrate-cms#18]
Update 3/25/19:

I think it is reasonable hypothesis that people who are looking to develop on Substrate are familiar with or have worked with Solidity in the past. People who are less technical may be able to evaluate which kinds of apps would be suitable as an Ethereum smart contract (business oriented) and those who are actual contract developers may have developed thought processes or patterns for smart contract development.

I want to have a doc which specifically targets these people who are "comfortable" with Ethereum, and states clearly the differences in thinking and development when building on substrate.

For example:
* What sorts of projects would be good for Ethereum Smart Contracts vs Substrate Runtime Module, and why?
* Substrate is inherently a fee-less system, and how that affects your development and functions you can build
* Storing only critical blockchain specific data on chain, not strings and other random stuff
* Bricking your chain with bad code
* Verify first, Write Last vs Revert
* How to write modular substrate modules versus how you might do the same with solidity
* etc...

**Comment by joepetrowski** [comment]
Closing this in favor of https://github.com/substrate-developer-hub/knowledgebase/issues/37

Smart contracts in general needs an overhaul and reconsideration of the content.
